### ISSUE TITLE
Botones sin accion

### ISSUE THREAD

**Issue by Nidev-lab** [msdario12/grupo-01-proyecto-final-rc#45]
## Proceso

1. Ingrese a la pagina.
2. Baje hasta el footer.

## Resultado esperado

• Que los botones que se encuentran en el footer redirijan a sus respectivos sitios.

## Resultado actual

• Los botones no cumplen ninguna acción.

## Captura

![image](https://github.com/msdario12/grupo-01-proyecto-final-rc/assets/53904695/c84d5d12-8c5a-4b4e-a961-6361564aa593)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by msdario12** [comment]
Se corrijen los enlaces del footer.
