### ISSUE TITLE
Formulario de turno

### ISSUE THREAD

**Issue by Nidev-lab** [msdario12/grupo-01-proyecto-final-rc#46]
## Proceso

1. Ingrese a la pagina.
2. Quise sacar un turno

## Resultado esperado

• Que no se puedan colocar números ni signos en lo datos (Nombre y apellido) solicitados.

## Resultado actual

• Se pueden colocar números y signos en dichos datos.

## Captura

![image](https://github.com/msdario12/grupo-01-proyecto-final-rc/assets/53904695/02e3438a-cf3f-4a01-930e-baaaa24c312e)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by msdario12** [comment]
Se corrige la validacion de los inputs para que solo admitan letras.
